export const Selectors = {
  home: {
    searchInput: '[data-testid="search-input"]',
    searchButton: '[data-testid="search-button"]',
    heroSection: '[data-testid="hero-section"]',
    featuredEvents: '[data-testid="featured-events"]',
    navMenu: '[data-testid="nav-menu"]',
    cookieBanner: '[data-testid="cookie-banner"]',
    acceptCookies: '[data-testid="accept-cookies"]',
  },
  event: {
    eventCard: '[data-testid="event-card"]',
    eventTitle: '[data-testid="event-title"]',
    eventDate: '[data-testid="event-date"]',
    eventLocation: '[data-testid="event-location"]',
    eventPrice: '[data-testid="event-price"]',
    buyTicketButton: '[data-testid="buy-ticket-btn"]',
    categoryFilter: '[data-testid="category-filter"]',
    sortDropdown: '[data-testid="sort-dropdown"]',
  },
  checkout: {
    seatSelector: '[data-testid="seat-selector"]',
    selectedSeat: '[data-testid="selected-seat"]',
    proceedButton: '[data-testid="proceed-btn"]',
    orderSummary: '[data-testid="order-summary"]',
    totalPrice: '[data-testid="total-price"]',
    paymentForm: '[data-testid="payment-form"]',
    cardNumber: '[data-testid="card-number"]',
    cardExpiry: '[data-testid="card-expiry"]',
    cardCvc: '[data-testid="card-cvc"]',
    confirmButton: '[data-testid="confirm-order-btn"]',
    successMessage: '[data-testid="booking-success"]',
  },
  auth: {
    loginButton: '[data-testid="login-btn"]',
    emailInput: '[data-testid="email-input"]',
    passwordInput: '[data-testid="password-input"]',
    submitLogin: '[data-testid="submit-login"]',
    logoutButton: '[data-testid="logout-btn"]',
    userMenu: '[data-testid="user-menu"]',
  },
  header: {
    logo: '[data-testid="header-logo"]',
    cartIcon: '[data-testid="cart-icon"]',
    cartCount: '[data-testid="cart-count"]',
  },
};
